### ISSUE TITLE
[Administrativo] Lecturas semanales

### ISSUE THREAD

**Issue by ferperezh** [PUC-RecSys-Class/RecSysPUC-2024-2#1]
Hola, tengo una duda sobre el plazo para leer las lecturas y hacer los comentarios. Por ejemplo, para la lectura de la semana del 19 de agosto, ¿hasta qué día y hora tenemos para completarlos? ¿Es hasta el lunes o martes antes de la clase?

Gracias de antemano y disculpa la confusión.

**Comment by denisparra** [comment]
Hola, es hasta el lunes 26 22:00 hrs.

Saludos
