### ISSUE TITLE
[Tarea 1] Version de python para pyreclab

### ISSUE THREAD

**Issue by PipeOlivares** [PUC-RecSys-Class/RecSysPUC-2024-2#4]
Buenas, 
He creado un jupyter notebook base para empezar a ejecutar los modelos de recomendación requeridos para la tarea, y al momento de intentar de instalar pyreclab me dice que: "no pudo encontrar una versión que satisface los requerimientos de pyreclab"
Entonces quería saber si pueden especificar para que versión de python está disponible la librería y así dejar instalada la versión correcta para ejecutarlo. Yo tengo en este momento Python3.12.5

**Comment by jalonsoluc** [comment]
Hola! Me pasó lo mismo (macOS)

**Comment by cmunhozc** [comment]
> Buenas, He creado un jupyter notebook base para empezar a ejecutar los modelos de recomendación requeridos para la tarea, y al momento de intentar de instalar pyreclab me dice que: "no pudo encontrar una versión que satisface los requerimientos de pyreclab" Entonces quería saber si pueden especificar para que versión de python está disponible la librería y así dejar instalada la versión correcta para ejecutarlo. Yo tengo en este momento Python3.12.5

Hola,
Imagino que estás tratando en local, en MacOS igual?. En general recomendamos trabajar siempre en Google Colab, ya que hemos probado los códigos y hemos trabajado con ellos en los prácticos. 
Frente al caso particular, revisaría primero la documentación https://github.com/gasevi/pyreclab…. , indica que está compilado en Python2.7, y tratar con los pasos sugeridos para macOS. Probaron esto?. 

Espero que ayuden los comentarios, 

Saludos
C.M.

**Comment by PipeOlivares** [comment]
Buenas,
Efectivamente lo estoy ejecutando en local. Por si alguien se enfrenta al mismo problema, se solucionó al ejecutarse con Python3.10.12!!
Saludos
